name: Build with CMake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: 3.1

    # Create build directory
    - name: Create build directory
      run: mkdir -p build

    # Configure with CMake and build
    - name: Configure and Build
      run: |
        cd build
        cmake ..

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          bin/*
          lib/*
        retention-days: 0
    
